name: SonarQube Scan

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  pull_request:

  workflow_dispatch:

env:
  CI: true

jobs:
  sonar_scanner:
    runs-on: [self-hosted, linux, docker, demu]
    steps:
      # This fixes the issue with the corrupted tzdata package
      - name: reinstall tzdata
        run: sudo apt-get install tzdata

      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          # Change the value to the PHP version you need
          php-version: '8.2'
          coverage: xdebug
          ini-values: date.timezone=Europe/Berlin

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # Enable this step if you need to update composer to v1
      # - name: Self update composer to v1
      #   run: composer self-update --1

      - name: Install dependencies with composer
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Run PHPStan
        run: composer phpstan:sonar || true

      - name: Run Psalm
        run: composer psalm-phar:sonar || composer psalm:sonar || true

      - name: Run tests with phpunit/phpunit
        run: composer test:coverage || true

      - name: Sonar Scanner
        uses: sonarsource/sonarcloud-github-action@master
